import { Tabs } from "expo-router"; // Add the correct import for Tabs
import React from "react";

export default function Layout() {
    return (
        <Tabs>
            <Tabs.Screen 
                name="index" 
                options={{title: 'Home', headerShown: false}} 
            />
            {/* Other tabs will be auto-generated by expo-router */}
            <Tabs.Screen
                name="profile" 
                options={{title: 'Profile', headerShown: false}}
            />  
        </Tabs>
    );
}